/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'inventario-edit-id': RouteRecordInfo<'inventario-edit-id', '/inventario/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'inventario-edit-invoice-product-edit-view': RouteRecordInfo<'inventario-edit-invoice-product-edit-view', '/inventario/edit/InvoiceProductEditView', Record<never, never>, Record<never, never>>,
    'inventario-ingreso': RouteRecordInfo<'inventario-ingreso', '/inventario/ingreso', Record<never, never>, Record<never, never>>,
    'inventario-ingreso-register': RouteRecordInfo<'inventario-ingreso-register', '/inventario/ingreso-register', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-ingreso-producto': RouteRecordInfo<'inventario-movimiento-ingreso-producto', '/inventario/movimiento/ingreso_producto', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-ingreso-registro-id': RouteRecordInfo<'inventario-movimiento-ingreso-registro-id', '/inventario/movimiento/ingreso_registro/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'inventario-movimiento-ingreso-registro-product-almacen': RouteRecordInfo<'inventario-movimiento-ingreso-registro-product-almacen', '/inventario/movimiento/ingreso_registro/ProductAlmacen', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-ingreso-registro-registro': RouteRecordInfo<'inventario-movimiento-ingreso-registro-registro', '/inventario/movimiento/ingreso_registro/registro', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-reporte': RouteRecordInfo<'inventario-movimiento-reporte', '/inventario/movimiento/reporte', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-salida-producto': RouteRecordInfo<'inventario-movimiento-salida-producto', '/inventario/movimiento/salida_producto', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-salida-registro-id': RouteRecordInfo<'inventario-movimiento-salida-registro-id', '/inventario/movimiento/salida_registro/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'inventario-movimiento-salida-registro-product-almacen': RouteRecordInfo<'inventario-movimiento-salida-registro-product-almacen', '/inventario/movimiento/salida_registro/ProductAlmacen', Record<never, never>, Record<never, never>>,
    'inventario-movimiento-salida-registro-registro': RouteRecordInfo<'inventario-movimiento-salida-registro-registro', '/inventario/movimiento/salida_registro/registro', Record<never, never>, Record<never, never>>,
    'inventario-preview-id': RouteRecordInfo<'inventario-preview-id', '/inventario/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'inventario-reporte': RouteRecordInfo<'inventario-reporte', '/inventario/reporte', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'producto-id': RouteRecordInfo<'producto-id', '/producto/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'producto-lista': RouteRecordInfo<'producto-lista', '/producto/lista', Record<never, never>, Record<never, never>>,
    'producto-reporte': RouteRecordInfo<'producto-reporte', '/producto/reporte', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
